# application-dev.yaml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database.public.yhm.cn:3306/db_passjava?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTCC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 25
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
  redis:
    host: redis.public.yhm.cn
    port: 6379
    password: 123456
    database: 0
    timeout: 3000
    lettuce:
      pool:
        max-idle: 8
        max-active: 25
        max-wait: 5000
  jackson:
    ## 格式为yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    ## 定时区，解决8小时的时间差问题
    time-zone: GMT+0
mybatis-plus:
  # 实体类位置
  type-aliases-package: cn.yhm.passjava.content.entity
  # mapper xml文件位置
  mapper-locations: classpath*:cn/passjava/**/mapper/xml/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段
      logic-delete-field: is_delete
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0